# Generated by Django 4.1.7 on 2023-04-14 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('construct', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('news_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('news_text', models.TextField()),
                ('house_id', models.IntegerField()),
                ('need_link', models.BooleanField(default=False)),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='construct.meetings')),
            ],
        ),
    ]
