# Generated by Django 4.1.7 on 2023-03-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='elections',
            fields=[
                ('election_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('voited_for', models.IntegerField(default=0)),
                ('voited_against', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='votes',
            fields=[
                ('vote_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('user_email', models.EmailField(max_length=254)),
                ('user_name', models.CharField(max_length=50)),
                ('user_flat', models.IntegerField()),
                ('election_id', models.IntegerField()),
                ('result', models.BooleanField()),
            ],
        ),
    ]
