# Generated by Django 4.1.7 on 2023-04-04 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='elections',
            fields=[
                ('election_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(default='Онлайн', max_length=10)),
                ('question', models.TextField()),
                ('voited_for_area', models.FloatField(default=0)),
                ('voited_against_area', models.FloatField(default=0)),
                ('voited_for_part', models.FloatField(default=0)),
                ('voited_against_part', models.FloatField(default=0)),
                ('quorum_limit', models.FloatField(default=50)),
                ('is_quorum', models.BooleanField(default=False)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.houses')),
            ],
        ),
        migrations.CreateModel(
            name='votes',
            fields=[
                ('vote_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('result', models.BooleanField()),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.elections')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='offline_votes',
            fields=[
                ('vote_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(default='Очное', max_length=10)),
                ('user_name', models.CharField(max_length=50)),
                ('user_flat_number', models.IntegerField(default=-1)),
                ('user_flat_area', models.FloatField(default=30)),
                ('user_flat_share', models.FloatField(default=1)),
                ('result', models.BooleanField()),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.elections')),
            ],
        ),
    ]
