# Generated by Django 4.1.7 on 2023-03-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elections',
            name='house_id',
            field=models.IntegerField(default=0),
        ),
    ]
