# Generated by Django 4.1.7 on 2023-04-03 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elections',
            name='type',
            field=models.CharField(default='Онлайн', max_length=10),
        ),
        migrations.AddField(
            model_name='offline_votes',
            name='type',
            field=models.CharField(default='Очное', max_length=10),
        ),
        migrations.AddField(
            model_name='offline_votes',
            name='user_flat_number',
            field=models.IntegerField(default=-1),
        ),
    ]
