# Generated by Django 4.1.7 on 2023-04-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='meetings',
            fields=[
                ('meeting_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stage', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('house_id', models.IntegerField()),
            ],
        ),
    ]
