# Generated by Django 4.1.7 on 2023-04-12 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construct', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='protocol',
            fields=[
                ('protocol_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('protocol_file', models.FileField(blank=True, null=True, upload_to='files/protocol/')),
            ],
        ),
        migrations.AddField(
            model_name='meetings',
            name='protocol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='construct.protocol'),
        ),
    ]
