# Generated by Django 4.1.7 on 2023-04-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construct', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetings',
            name='initiator_id',
            field=models.IntegerField(default=0),
        ),
    ]
