# Generated by Django 4.1.7 on 2023-04-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houses',
            name='house_area',
            field=models.FloatField(default=1000),
        ),
    ]
