# Generated by Django 4.1.7 on 2023-04-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houses',
            name='inn',
            field=models.CharField(default='', max_length=13),
        ),
    ]
